name: Lab 13 - Self Hosted Runner Test

on:
  push:
    branches:
      - lab13-integration
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Check Python
        shell: powershell
        run: python --version

      - name: Check Git
        shell: powershell
        run: git --version

      - name: Check Docker
        shell: powershell
        run: docker info

      - name: Check Kubernetes
        shell: powershell
        run: kubectl get nodes

      - name: Check Project
        shell: powershell
        run: |
          Write-Host "Runner: $env:RUNNER_NAME"
          Write-Host "Workspace: $env:GITHUB_WORKSPACE"
          Test-Path "C:\Users\jnane\Favorites\churn-prediction"